package co.gov.bogota.sed.sigcon.web.exception;

public enum ErrorCode {
    // I1
    USUARIO_NO_ENCONTRADO,
    CONTRATO_NO_ENCONTRADO,
    NUMERO_CONTRATO_DUPLICADO,
    EMAIL_DUPLICADO,
    ACCESO_DENEGADO,
    FORMATO_IMAGEN_INVALIDO,
    ESTADO_INVALIDO,

    // I2
    INFORME_NO_ENCONTRADO,
    INFORME_NO_EDITABLE,
    TRANSICION_INVALIDA,
    OBSERVACION_REQUERIDA,
    ACTIVIDAD_REQUERIDA,
    PORCENTAJE_INVALIDO,
    SOPORTE_INVALIDO,
    DOCUMENTO_ADICIONAL_REQUERIDO,
    CONTRATO_NO_ACTIVO
}
