package co.gov.bogota.sed.sigcon.web.exception;

public enum ErrorCode {
    // I1
    USUARIO_NO_ENCONTRADO,
    CONTRATO_NO_ENCONTRADO,
    NUMERO_CONTRATO_DUPLICADO,
    EMAIL_DUPLICADO,
    ACCESO_DENEGADO,
    FORMATO_IMAGEN_INVALIDO,
    ESTADO_INVALIDO,

    // I2
    INFORME_NO_ENCONTRADO,
    INFORME_NO_EDITABLE,
    TRANSICION_INVALIDA,
    OBSERVACION_REQUERIDA,
    ACTIVIDAD_REQUERIDA,
    PORCENTAJE_INVALIDO,
    SOPORTE_INVALIDO,
    DOCUMENTO_ADICIONAL_REQUERIDO,
    CONTRATO_NO_ACTIVO,

    // I3
    PDF_NO_DISPONIBLE,
    PDF_GENERACION_FALLIDA,
    FIRMA_REQUERIDA,
    NOTIFICACION_NO_ENCONTRADA,
    EMAIL_NO_ENVIADO,
    OPERACION_NO_PERMITIDA,

    // I4
    FECHA_FIN_INVALIDA,

    // I7
    DOCUMENTO_REQUERIDO_NO_ENCONTRADO,
    DOCUMENTO_REQUERIDO_FORMATO_INVALIDO,
    DOCUMENTO_REQUERIDO_NO_EDITABLE,
    DOCUMENTO_REQUERIDO_FALTANTE,

    // I-SEC
    SOPORTE_FORMATO_INVALIDO,
    SOPORTE_TAMANIO_EXCEDIDO,

    // I16
    INFORME_CARGA_BLOQUEADA
}
