-- ============================================================
-- SIGCON I1 — DDL Schema Setup
-- Schema: SED_SIGCON · Table prefix: SGCN_
-- ============================================================

-- SGCN_USUARIOS
CREATE SEQUENCE SGCN_USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_USUARIOS (
    ID              NUMBER          DEFAULT SGCN_USUARIOS_SEQ.NEXTVAL PRIMARY KEY,
    EMAIL           VARCHAR2(200)   NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    CARGO           VARCHAR2(200),
    ROL             VARCHAR2(20)    NOT NULL,
    FIRMA_IMAGEN    VARCHAR2(500),
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_USUARIOS_ROL CHECK (ROL IN ('CONTRATISTA','REVISOR','SUPERVISOR','ADMIN'))
);

CREATE INDEX IDX_USUARIOS_EMAIL ON SGCN_USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_ROL   ON SGCN_USUARIOS(ROL);

CREATE OR REPLACE TRIGGER TRG_USUARIOS_AUDIT
BEFORE UPDATE ON SGCN_USUARIOS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- SGCN_CONTRATOS
CREATE SEQUENCE SGCN_CONTRATOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_CONTRATOS (
    ID                  NUMBER          DEFAULT SGCN_CONTRATOS_SEQ.NEXTVAL PRIMARY KEY,
    NUMERO              VARCHAR2(50)    NOT NULL UNIQUE,
    OBJETO              VARCHAR2(1000)  NOT NULL,
    TIPO                VARCHAR2(20)    DEFAULT 'OPS' NOT NULL,
    VALOR_TOTAL         NUMBER(18,2)    NOT NULL,
    FECHA_INICIO        DATE            NOT NULL,
    FECHA_FIN           DATE            NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'EN_EJECUCION' NOT NULL,
    ID_CONTRATISTA      NUMBER          NOT NULL,
    ID_REVISOR          NUMBER,
    ID_SUPERVISOR       NUMBER,
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(200),
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT FK_CONTRATOS_CONTRATISTA FOREIGN KEY (ID_CONTRATISTA) REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT FK_CONTRATOS_REVISOR     FOREIGN KEY (ID_REVISOR)     REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT FK_CONTRATOS_SUPERVISOR  FOREIGN KEY (ID_SUPERVISOR)  REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT CHK_CONTRATOS_ESTADO     CHECK (ESTADO IN ('EN_EJECUCION','LIQUIDADO','CERRADO')),
    CONSTRAINT CHK_CONTRATOS_TIPO       CHECK (TIPO IN ('OPS'))
);

CREATE INDEX IDX_CONTRATOS_CONTRATISTA ON SGCN_CONTRATOS(ID_CONTRATISTA);
CREATE INDEX IDX_CONTRATOS_SUPERVISOR  ON SGCN_CONTRATOS(ID_SUPERVISOR);
CREATE INDEX IDX_CONTRATOS_REVISOR    ON SGCN_CONTRATOS(ID_REVISOR);
CREATE INDEX IDX_CONTRATOS_ESTADO      ON SGCN_CONTRATOS(ESTADO);

CREATE OR REPLACE TRIGGER TRG_CONTRATOS_AUDIT
BEFORE UPDATE ON SGCN_CONTRATOS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- SGCN_OBLIGACIONES
CREATE SEQUENCE SGCN_OBLIGACIONES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_OBLIGACIONES (
    ID              NUMBER          DEFAULT SGCN_OBLIGACIONES_SEQ.NEXTVAL PRIMARY KEY,
    ID_CONTRATO     NUMBER          NOT NULL,
    DESCRIPCION     VARCHAR2(2000)  NOT NULL,
    ORDEN           NUMBER          NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_OBLIGACIONES_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES SGCN_CONTRATOS(ID)
);

CREATE INDEX IDX_OBLIGACIONES_CONTRATO ON SGCN_OBLIGACIONES(ID_CONTRATO);

CREATE OR REPLACE TRIGGER TRG_OBLIGACIONES_AUDIT
BEFORE UPDATE ON SGCN_OBLIGACIONES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- SGCN_DOCS_CATALOGO
CREATE SEQUENCE SGCN_DOCS_CATALOGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_DOCS_CATALOGO (
    ID              NUMBER          DEFAULT SGCN_DOCS_CATALOGO_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    OBLIGATORIO     NUMBER(1)       DEFAULT 0 NOT NULL,
    TIPO_CONTRATO   VARCHAR2(20)    DEFAULT 'OPS' NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_DOCS_CATALOGO_TIPO CHECK (TIPO_CONTRATO IN ('OPS'))
);

CREATE OR REPLACE TRIGGER TRG_DOCS_CATALOGO_AUDIT
BEFORE UPDATE ON SGCN_DOCS_CATALOGO FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/
