-- ============================================================
-- SIGCON I1 — DDL Schema Setup
-- Schema: SED_SIGCON · Oracle 19c+
-- ============================================================
-- PREREQUISITES:
--   - Connected as SED_SIGCON schema owner
--   - Oracle 19c+ (uses TIMESTAMP DEFAULT SYSTIMESTAMP syntax)
-- NOT IDEMPOTENT: Re-running fails with ORA-00955. Use a fresh schema.
-- EXECUTION ORDER: Run 00_setup.sql before 01_datos_prueba.sql
-- DO NOT execute in production without DBA review.
-- ============================================================

-- SGCN_USUARIOS
CREATE SEQUENCE SGCN_USUARIOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_USUARIOS (
    ID              NUMBER          DEFAULT SGCN_USUARIOS_SEQ.NEXTVAL PRIMARY KEY,
    EMAIL           VARCHAR2(200)   NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    CARGO           VARCHAR2(200),
    ROL             VARCHAR2(20)    NOT NULL,
    FIRMA_IMAGEN    VARCHAR2(500),
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_USUARIOS_ROL CHECK (ROL IN ('CONTRATISTA','REVISOR','SUPERVISOR','ADMIN'))
);

CREATE INDEX IDX_USUARIOS_EMAIL ON SGCN_USUARIOS(EMAIL);
CREATE INDEX IDX_USUARIOS_ROL   ON SGCN_USUARIOS(ROL);

CREATE OR REPLACE TRIGGER TRG_USUARIOS_AUDIT
BEFORE UPDATE ON SGCN_USUARIOS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- SGCN_CONTRATOS
CREATE SEQUENCE SGCN_CONTRATOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_CONTRATOS (
    ID                  NUMBER          DEFAULT SGCN_CONTRATOS_SEQ.NEXTVAL PRIMARY KEY,
    NUMERO              VARCHAR2(50)    NOT NULL UNIQUE,
    OBJETO              VARCHAR2(1000)  NOT NULL,
    TIPO                VARCHAR2(20)    DEFAULT 'OPS' NOT NULL,
    VALOR_TOTAL         NUMBER(18,2)    NOT NULL,
    FECHA_INICIO        DATE            NOT NULL,
    FECHA_FIN           DATE            NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'EN_EJECUCION' NOT NULL,
    ID_CONTRATISTA      NUMBER          NOT NULL,
    ID_REVISOR          NUMBER,
    ID_SUPERVISOR       NUMBER,
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(200),
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT FK_CONTRATOS_CONTRATISTA FOREIGN KEY (ID_CONTRATISTA) REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT FK_CONTRATOS_REVISOR     FOREIGN KEY (ID_REVISOR)     REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT FK_CONTRATOS_SUPERVISOR  FOREIGN KEY (ID_SUPERVISOR)  REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT CHK_CONTRATOS_ESTADO     CHECK (ESTADO IN ('EN_EJECUCION','LIQUIDADO','CERRADO')),
    CONSTRAINT CHK_CONTRATOS_TIPO       CHECK (TIPO IN ('OPS'))
);

CREATE INDEX IDX_CONTRATOS_CONTRATISTA ON SGCN_CONTRATOS(ID_CONTRATISTA);
CREATE INDEX IDX_CONTRATOS_SUPERVISOR  ON SGCN_CONTRATOS(ID_SUPERVISOR);
CREATE INDEX IDX_CONTRATOS_REVISOR    ON SGCN_CONTRATOS(ID_REVISOR);     -- forward-compat: I2 reviewer queues filter by ID_REVISOR
CREATE INDEX IDX_CONTRATOS_ESTADO      ON SGCN_CONTRATOS(ESTADO);

CREATE OR REPLACE TRIGGER TRG_CONTRATOS_AUDIT
BEFORE UPDATE ON SGCN_CONTRATOS FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- SGCN_OBLIGACIONES
CREATE SEQUENCE SGCN_OBLIGACIONES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_OBLIGACIONES (
    ID              NUMBER          DEFAULT SGCN_OBLIGACIONES_SEQ.NEXTVAL PRIMARY KEY,
    ID_CONTRATO     NUMBER          NOT NULL,
    DESCRIPCION     VARCHAR2(2000)  NOT NULL,
    ORDEN           NUMBER          NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_OBLIGACIONES_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES SGCN_CONTRATOS(ID)
);

CREATE INDEX IDX_OBLIGACIONES_CONTRATO ON SGCN_OBLIGACIONES(ID_CONTRATO);

CREATE OR REPLACE TRIGGER TRG_OBLIGACIONES_AUDIT
BEFORE UPDATE ON SGCN_OBLIGACIONES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- SGCN_DOCS_CATALOGO
CREATE SEQUENCE SGCN_DOCS_CATALOGO_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_DOCS_CATALOGO (
    ID              NUMBER          DEFAULT SGCN_DOCS_CATALOGO_SEQ.NEXTVAL PRIMARY KEY,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    OBLIGATORIO     NUMBER(1)       DEFAULT 0 NOT NULL,
    TIPO_CONTRATO   VARCHAR2(20)    DEFAULT 'OPS' NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT CHK_DOCS_CATALOGO_TIPO CHECK (TIPO_CONTRATO IN ('OPS'))
);

CREATE OR REPLACE TRIGGER TRG_DOCS_CATALOGO_AUDIT
BEFORE UPDATE ON SGCN_DOCS_CATALOGO FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

CREATE INDEX IDX_DOCS_CATALOGO_TIPO ON SGCN_DOCS_CATALOGO(TIPO_CONTRATO);

-- ============================================================
-- ===== INCREMENTO 2 =====
-- SIGCON I2 — Informes y Flujo de Aprobacion
-- Spec: docs/specs/2026-05-01-sigcon-i2-spec.md §3
-- ============================================================

-- ----- SGCN_INFORMES -----
CREATE SEQUENCE SGCN_INFORMES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_INFORMES (
    ID                  NUMBER          DEFAULT SGCN_INFORMES_SEQ.NEXTVAL PRIMARY KEY,
    ID_CONTRATO         NUMBER          NOT NULL,
    NUMERO              NUMBER          NOT NULL,
    FECHA_INICIO        DATE            NOT NULL,
    FECHA_FIN           DATE            NOT NULL,
    ESTADO              VARCHAR2(20)    DEFAULT 'BORRADOR' NOT NULL,
    FECHA_CREACION      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    FECHA_ULTIMO_ENVIO  TIMESTAMP,
    FECHA_APROBACION    TIMESTAMP,
    PDF_RUTA            VARCHAR2(500),
    ACTIVO              NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT          TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY          VARCHAR2(200),
    UPDATED_AT          TIMESTAMP,
    CONSTRAINT FK_INFORMES_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES SGCN_CONTRATOS(ID),
    CONSTRAINT UQ_INFORMES_CONTRATO_NUMERO UNIQUE (ID_CONTRATO, NUMERO),
    CONSTRAINT CHK_INFORMES_ESTADO CHECK (ESTADO IN ('BORRADOR','ENVIADO','EN_REVISION','DEVUELTO','APROBADO')),
    CONSTRAINT CHK_INFORMES_PERIODO CHECK (FECHA_FIN >= FECHA_INICIO)
);

CREATE INDEX IDX_INFORMES_CONTRATO ON SGCN_INFORMES(ID_CONTRATO);
CREATE INDEX IDX_INFORMES_ESTADO   ON SGCN_INFORMES(ESTADO);

CREATE OR REPLACE TRIGGER TRG_INFORMES_AUDIT
BEFORE UPDATE ON SGCN_INFORMES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- ----- SGCN_ACTIVIDADES -----
CREATE SEQUENCE SGCN_ACTIVIDADES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_ACTIVIDADES (
    ID              NUMBER          DEFAULT SGCN_ACTIVIDADES_SEQ.NEXTVAL PRIMARY KEY,
    ID_INFORME      NUMBER          NOT NULL,
    ID_OBLIGACION   NUMBER          NOT NULL,
    DESCRIPCION     VARCHAR2(3000)  NOT NULL,
    PORCENTAJE      NUMBER(5,2)     NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_ACTIVIDADES_INFORME FOREIGN KEY (ID_INFORME) REFERENCES SGCN_INFORMES(ID),
    CONSTRAINT FK_ACTIVIDADES_OBLIGACION FOREIGN KEY (ID_OBLIGACION) REFERENCES SGCN_OBLIGACIONES(ID),
    CONSTRAINT CHK_ACTIVIDADES_PORCENTAJE CHECK (PORCENTAJE >= 0 AND PORCENTAJE <= 100)
);

CREATE INDEX IDX_ACTIVIDADES_INFORME ON SGCN_ACTIVIDADES(ID_INFORME);

CREATE OR REPLACE TRIGGER TRG_ACTIVIDADES_AUDIT
BEFORE UPDATE ON SGCN_ACTIVIDADES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- ----- SGCN_SOPORTES -----
CREATE SEQUENCE SGCN_SOPORTES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_SOPORTES (
    ID              NUMBER          DEFAULT SGCN_SOPORTES_SEQ.NEXTVAL PRIMARY KEY,
    ID_ACTIVIDAD    NUMBER          NOT NULL,
    TIPO            VARCHAR2(20)    NOT NULL,
    NOMBRE          VARCHAR2(200)   NOT NULL,
    REFERENCIA      VARCHAR2(1000)  NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_SOPORTES_ACTIVIDAD FOREIGN KEY (ID_ACTIVIDAD) REFERENCES SGCN_ACTIVIDADES(ID),
    CONSTRAINT CHK_SOPORTES_TIPO CHECK (TIPO IN ('ARCHIVO','URL'))
);

CREATE INDEX IDX_SOPORTES_ACTIVIDAD ON SGCN_SOPORTES(ID_ACTIVIDAD);

CREATE OR REPLACE TRIGGER TRG_SOPORTES_AUDIT
BEFORE UPDATE ON SGCN_SOPORTES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- ----- SGCN_DOCS_ADICIONALES -----
CREATE SEQUENCE SGCN_DOCS_ADICIONALES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_DOCS_ADICIONALES (
    ID              NUMBER          DEFAULT SGCN_DOCS_ADICIONALES_SEQ.NEXTVAL PRIMARY KEY,
    ID_INFORME      NUMBER          NOT NULL,
    ID_CATALOGO     NUMBER          NOT NULL,
    REFERENCIA      VARCHAR2(1000)  NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_DOCS_ADICIONALES_INFORME FOREIGN KEY (ID_INFORME) REFERENCES SGCN_INFORMES(ID),
    CONSTRAINT FK_DOCS_ADICIONALES_CATALOGO FOREIGN KEY (ID_CATALOGO) REFERENCES SGCN_DOCS_CATALOGO(ID)
);

CREATE INDEX IDX_DOCS_ADICIONALES_INFORME ON SGCN_DOCS_ADICIONALES(ID_INFORME);

CREATE OR REPLACE TRIGGER TRG_DOCS_ADICIONALES_AUDIT
BEFORE UPDATE ON SGCN_DOCS_ADICIONALES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/

-- ----- SGCN_OBSERVACIONES -----
CREATE SEQUENCE SGCN_OBSERVACIONES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_OBSERVACIONES (
    ID              NUMBER          DEFAULT SGCN_OBSERVACIONES_SEQ.NEXTVAL PRIMARY KEY,
    ID_INFORME      NUMBER          NOT NULL,
    TEXTO           VARCHAR2(2000)  NOT NULL,
    AUTOR_ROL       VARCHAR2(20)    NOT NULL,
    FECHA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    ACTIVO          NUMBER(1)       DEFAULT 1 NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_OBSERVACIONES_INFORME FOREIGN KEY (ID_INFORME) REFERENCES SGCN_INFORMES(ID),
    CONSTRAINT CHK_OBSERVACIONES_ROL CHECK (AUTOR_ROL IN ('REVISOR','SUPERVISOR'))
);

CREATE INDEX IDX_OBSERVACIONES_INFORME ON SGCN_OBSERVACIONES(ID_INFORME);

CREATE OR REPLACE TRIGGER TRG_OBSERVACIONES_AUDIT
BEFORE UPDATE ON SGCN_OBSERVACIONES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/


-- ============================================================
-- ===== INCREMENTO 3 -- PDF, Firmas, Notificaciones =========
-- ============================================================

-- ----- Extender SGCN_INFORMES con metadatos PDF -----
-- PDF_RUTA ya existe (nullable) desde I2; se agregan metadatos de inmutabilidad.
ALTER TABLE SGCN_INFORMES ADD (
    PDF_GENERADO_AT  TIMESTAMP,
    PDF_HASH         VARCHAR2(128)
);

CREATE INDEX IDX_INFORMES_PDF_GENERADO ON SGCN_INFORMES(PDF_GENERADO_AT);

-- ----- SGCN_NOTIFICACIONES -----
CREATE SEQUENCE SGCN_NOTIFICACIONES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE TABLE SGCN_NOTIFICACIONES (
    ID              NUMBER          DEFAULT SGCN_NOTIFICACIONES_SEQ.NEXTVAL PRIMARY KEY,
    ID_USUARIO      NUMBER          NOT NULL,
    TITULO          VARCHAR2(200)   NOT NULL,
    DESCRIPCION     VARCHAR2(1000)  NOT NULL,
    TIPO_EVENTO     VARCHAR2(50)    NOT NULL,
    ID_INFORME      NUMBER,
    LEIDA           NUMBER(1)       DEFAULT 0 NOT NULL,
    FECHA           TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY      VARCHAR2(200),
    UPDATED_AT      TIMESTAMP,
    CONSTRAINT FK_NOTIFICACIONES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES SGCN_USUARIOS(ID),
    CONSTRAINT FK_NOTIFICACIONES_INFORME FOREIGN KEY (ID_INFORME) REFERENCES SGCN_INFORMES(ID),
    CONSTRAINT CHK_NOTIFICACIONES_LEIDA CHECK (LEIDA IN (0,1)),
    CONSTRAINT CHK_NOTIFICACIONES_EVENTO CHECK (TIPO_EVENTO IN (
        'INFORME_ENVIADO',
        'REVISION_APROBADA',
        'REVISION_DEVUELTA',
        'INFORME_APROBADO',
        'INFORME_DEVUELTO'
    ))
);

CREATE INDEX IDX_NOTIFICACIONES_USUARIO ON SGCN_NOTIFICACIONES(ID_USUARIO);
CREATE INDEX IDX_NOTIFICACIONES_LEIDA   ON SGCN_NOTIFICACIONES(LEIDA);

CREATE OR REPLACE TRIGGER TRG_NOTIFICACIONES_AUDIT
BEFORE UPDATE ON SGCN_NOTIFICACIONES FOR EACH ROW
BEGIN :NEW.UPDATED_AT := SYSTIMESTAMP; END;
/
