-- ============================================================
-- SIGCON - Reset local de informes
-- Uso: ambientes locales/de prueba. No ejecutar en produccion.
--
-- Objetivo:
--   Eliminar informes creados durante pruebas funcionales y todas sus
--   relaciones dependientes, sin tocar usuarios, contratos, obligaciones
--   ni catalogos documentales.
--
-- Para ejecutar, cambie la siguiente linea a:
--   DEFINE SIGCON_RESET_INFORMES_CONFIRM = 'RESET_INFORMES'
-- ============================================================

DEFINE SIGCON_RESET_INFORMES_CONFIRM = 'NO'

SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT ROLLBACK

DECLARE
    v_confirmacion VARCHAR2(50) := UPPER(TRIM('&SIGCON_RESET_INFORMES_CONFIRM'));
BEGIN
    IF v_confirmacion <> 'RESET_INFORMES' THEN
        RAISE_APPLICATION_ERROR(
            -20000,
            'Reset cancelado. Cambie SIGCON_RESET_INFORMES_CONFIRM a RESET_INFORMES para ejecutar.'
        );
    END IF;
END;
/

PROMPT ===== Conteos antes del reset =====
SELECT 'SGCN_INFORMES' tabla, COUNT(*) total FROM SGCN_INFORMES
UNION ALL SELECT 'SGCN_ACTIVIDADES', COUNT(*) FROM SGCN_ACTIVIDADES
UNION ALL SELECT 'SGCN_SOPORTES', COUNT(*) FROM SGCN_SOPORTES
UNION ALL SELECT 'SGCN_DOCS_ADICIONALES', COUNT(*) FROM SGCN_DOCS_ADICIONALES
UNION ALL SELECT 'SGCN_DOCS_REQUERIDOS', COUNT(*) FROM SGCN_DOCS_REQUERIDOS
UNION ALL SELECT 'SGCN_OBSERVACIONES', COUNT(*) FROM SGCN_OBSERVACIONES
UNION ALL SELECT 'SGCN_NOTIFICACIONES con informe', COUNT(*) FROM SGCN_NOTIFICACIONES WHERE ID_INFORME IS NOT NULL
UNION ALL SELECT 'SGCN_APORTES_SGSSI', COUNT(*) FROM SGCN_APORTES_SGSSI;

SAVEPOINT reset_informes_local_dev;

DELETE FROM SGCN_SOPORTES
WHERE ID_ACTIVIDAD IN (
    SELECT A.ID
    FROM SGCN_ACTIVIDADES A
    WHERE A.ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I)
);

DELETE FROM SGCN_APORTES_SGSSI
WHERE ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I);

DELETE FROM SGCN_DOCS_ADICIONALES
WHERE ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I);

DELETE FROM SGCN_DOCS_REQUERIDOS
WHERE ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I);

DELETE FROM SGCN_OBSERVACIONES
WHERE ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I);

DELETE FROM SGCN_NOTIFICACIONES
WHERE ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I);

DELETE FROM SGCN_ACTIVIDADES
WHERE ID_INFORME IN (SELECT I.ID FROM SGCN_INFORMES I);

DELETE FROM SGCN_INFORMES;

DECLARE
    v_parametros_existe NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_parametros_existe
    FROM USER_TABLES
    WHERE TABLE_NAME = 'SGCN_PARAMETROS';

    IF v_parametros_existe > 0 THEN
        MERGE INTO SGCN_PARAMETROS p
        USING (
            SELECT
                'VB_ACTIVO' AS CLAVE,
                'S' AS VALOR,
                'Visto Bueno Administrativo activo en el flujo de informes' AS DESCRIPCION
            FROM DUAL
        ) src
        ON (p.CLAVE = src.CLAVE)
        WHEN MATCHED THEN
            UPDATE SET p.VALOR = src.VALOR, p.DESCRIPCION = src.DESCRIPCION
        WHEN NOT MATCHED THEN
            INSERT (CLAVE, VALOR, DESCRIPCION)
            VALUES (src.CLAVE, src.VALOR, src.DESCRIPCION);
    END IF;
END;
/

DECLARE
    v_restantes NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO v_restantes
    FROM (
        SELECT ID FROM SGCN_INFORMES
        UNION ALL
        SELECT A.ID FROM SGCN_ACTIVIDADES A
        UNION ALL
        SELECT S.ID FROM SGCN_SOPORTES S
        UNION ALL
        SELECT D.ID FROM SGCN_DOCS_ADICIONALES D
        UNION ALL
        SELECT R.ID FROM SGCN_DOCS_REQUERIDOS R
        UNION ALL
        SELECT O.ID FROM SGCN_OBSERVACIONES O
        UNION ALL
        SELECT N.ID FROM SGCN_NOTIFICACIONES N WHERE N.ID_INFORME IS NOT NULL
        UNION ALL
        SELECT P.ID FROM SGCN_APORTES_SGSSI P
    );

    IF v_restantes <> 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'Reset incompleto: aun existen registros dependientes de informes.'
        );
    END IF;
END;
/

COMMIT;

PROMPT ===== Conteos despues del reset =====
SELECT 'SGCN_INFORMES' tabla, COUNT(*) total FROM SGCN_INFORMES
UNION ALL SELECT 'SGCN_ACTIVIDADES', COUNT(*) FROM SGCN_ACTIVIDADES
UNION ALL SELECT 'SGCN_SOPORTES', COUNT(*) FROM SGCN_SOPORTES
UNION ALL SELECT 'SGCN_DOCS_ADICIONALES', COUNT(*) FROM SGCN_DOCS_ADICIONALES
UNION ALL SELECT 'SGCN_DOCS_REQUERIDOS', COUNT(*) FROM SGCN_DOCS_REQUERIDOS
UNION ALL SELECT 'SGCN_OBSERVACIONES', COUNT(*) FROM SGCN_OBSERVACIONES
UNION ALL SELECT 'SGCN_NOTIFICACIONES con informe', COUNT(*) FROM SGCN_NOTIFICACIONES WHERE ID_INFORME IS NOT NULL
UNION ALL SELECT 'SGCN_APORTES_SGSSI', COUNT(*) FROM SGCN_APORTES_SGSSI;

PROMPT Reset de informes finalizado.
