SET SERVEROUTPUT ON;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'SGCN_INFORMES'
       AND COLUMN_NAME = 'FECHA_ELABORACION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'ALTER TABLE SGCN_INFORMES ADD (FECHA_ELABORACION DATE DEFAULT NULL)';
        DBMS_OUTPUT.PUT_LINE('OK: columna SGCN_INFORMES.FECHA_ELABORACION creada.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('SKIP: columna SGCN_INFORMES.FECHA_ELABORACION ya existe.');
    END IF;
END;
/

PROMPT OK: migracion incremental I8 aplicada.
