-- I12: control de carga de informes y evento de notificacion masiva.

MERGE INTO SGCN_PARAMETROS p
USING (SELECT 'CARGA_INFORMES_ACTIVA' CLAVE FROM DUAL) s
ON (p.CLAVE = s.CLAVE)
WHEN NOT MATCHED THEN
  INSERT (CLAVE, VALOR, DESCRIPCION)
  VALUES (
    'CARGA_INFORMES_ACTIVA',
    'true',
    'Habilita la creacion de nuevos informes por contratistas'
  );

ALTER TABLE SGCN_NOTIFICACIONES DROP CONSTRAINT CHK_NOTIFICACIONES_EVENTO;

ALTER TABLE SGCN_NOTIFICACIONES ADD CONSTRAINT CHK_NOTIFICACIONES_EVENTO CHECK (
  TIPO_EVENTO IN (
    'INFORME_ENVIADO',
    'REVISION_APROBADA',
    'REVISION_DEVUELTA',
    'INFORME_APROBADO',
    'INFORME_DEVUELTO',
    'INFORME_EN_VISTO_BUENO',
    'VB_DADO',
    'VB_ESCALADO',
    'VB_DEVUELTO',
    'CARGA_INFORMES_DESACTIVADA'
  )
);

COMMIT;
