export const SED_DEPENDENCIAS: string[] = [
  'Despacho del Secretario(a) de Educación',
  'Oficina Asesora de Comunicaciones y Prensa',
  'Oficina Asesora Jurídica',
  'Oficina Asesora de Planeación',
  'Oficina de Control Interno',
  'Subsecretaría de Acceso y Permanencia',
  'Subsecretaría de Calidad y Pertinencia',
  'Subsecretaría de Gestión Institucional',
  'Subsecretaría de Integración Interinstitucional',
  'Dirección de Bienestar Estudiantil',
  'Dirección de Cobertura',
  'Dirección de Evaluación de la Educación',
  'Dirección de Formación de Docentes e Innovación Pedagógica',
  'Dirección de Talento Humano',
  'Dirección de Gestión Contractual',
  'Dirección de Planeación y Estadísticas',
  'Dirección de Tecnología e Informática',
  'Dirección Financiera',
  'Dirección de Inspección y Vigilancia',
  'Subdirección de Gestión Contractual',
  'Subdirección de Diseño, Evaluación y Sistematización Curricular',
  'Subdirección de Estándares y Evaluación',
  'Subdirección de Ambientes Escolares',
  'Subdirección Administrativa y Financiera',
  'Dirección Local de Educación Usaquén',
  'Dirección Local de Educación Chapinero',
  'Dirección Local de Educación Santafé',
  'Dirección Local de Educación San Cristóbal',
  'Dirección Local de Educación Usme',
  'Dirección Local de Educación Tunjuelito',
  'Dirección Local de Educación Bosa',
  'Dirección Local de Educación Kennedy',
  'Dirección Local de Educación Fontibón',
  'Dirección Local de Educación Engativá',
  'Dirección Local de Educación Suba',
  'Dirección Local de Educación Barrios Unidos',
  'Dirección Local de Educación Teusaquillo',
  'Dirección Local de Educación Los Mártires',
  'Dirección Local de Educación Antonio Nariño',
  'Dirección Local de Educación Puente Aranda',
  'Dirección Local de Educación La Candelaria',
  'Dirección Local de Educación Rafael Uribe Uribe',
  'Dirección Local de Educación Ciudad Bolívar',
  'Dirección Local de Educación Sumapaz',
];
